// PAGE
export const SET_PAGE = 'SET_PAGE';

// APK
export const GET_APK = 'GET_APK';
export const DELETE_APK = 'DELETE_APK';
export const SELECT_APK = 'SELECT_APK';

// DETECTION
export const SET_DETECTION_LOADING = 'SET_DETECTION_LOADING';
export const GET_DETECTION = 'GET_DETECTION';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

// CONFIGURATION
export const GET_CONFIGURATION = 'GET_CONFIGURATION';
export const DELETE_CONFIGURATION = 'DELETE_CONFIGURATION';
